# Load default processing options
imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }
  - { resource: "EXT:xo/Configuration/RTE/XoDefault.yaml" }

editor:
  config:
    contentsCss:
      - 'EXT:rte_ckeditor/Resources/Public/Css/contents.css'
      - '/assets/css/editor.css'
      -
    stylesSet:
      - { name: 'LLL:EXT:xna/Resources/Private/Language/locallang_rte.xlf:tx_xna_rte.link.download', element: 'a', attributes: { class: 'link--download' } }
      - { name: 'LLL:EXT:xna/Resources/Private/Language/locallang_rte.xlf:tx_xna_rte.link.cta', element: 'a', attributes: { class: 'link--cta' } }
      - { name: 'LLL:EXT:xna/Resources/Private/Language/locallang_rte.xlf:tx_xna_rte.text.small', element: 'span', attributes: { class: 'text--small' } }
      - { name: 'LLL:EXT:xna/Resources/Private/Language/locallang_rte.xlf:tx_xna_rte.text.large', element: 'span', attributes: { class: 'text--large' } }

buttons:
  link:
    properties:
      class:
        allowedClasses: 'link--download, link--external, link--mail, link--phone, link--cta'

classesAnchor:
  linkCtaInternal:
    class: 'link--cta'
    type: 'page'