imports:
  - { resource: 'EXT:xo/Configuration/Sites/Default.yaml' }
websiteTitle: 'Landschaftspflege Oberland'
baseVariants:
  -
    base: 'http://landschaftspflege-oberland.local/'
    condition: 'applicationContext == "Development"'
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=49'
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /vendor/\r\nDisallow: /typo3_src/\r\nSitemap: http://landschaftspflege-oberland.local/sitemap.xml"