imports:
  - { resource: 'EXT:xo/Configuration/Sites/Default.yaml' }
websiteTitle: 'Kist Escherich'
baseVariants:
  - base: 'http://kist-escherich.local'
    condition: 'applicationContext == "Development"'
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=47'
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /vendor/\r\nDisallow: /typo3_src/\r\nSitemap: http://xna.local/sitemap.xml"